"""引导用户首次写 ~/.web-publish/.env (urllib backend 用)."""
from __future__ import annotations

import os
from pathlib import Path


GUIDE = """\
=== web-publish setup ===

`urllib` backend 需要 cookie + uuid 写到 ~/.web-publish/.env。
（如果你用 `opencli-bridge` backend，不需要做这一步 —— 浏览器同源带 cookie。）

两种 cookie 抓取方式：

方式 A — Cookie-Editor extension (推荐):
  1. Chrome Web Store 装 "Cookie-Editor" (>1M 用户)
  2. 打开 https://juejin.cn (已登录)
  3. 点 Cookie-Editor icon → Export → 选 "Header String"
  4. 整个字符串粘到下面

方式 B — Chrome DevTools 手抓:
  1. F12 → Application → Cookies → https://juejin.cn
  2. 复制每行 name=value 拼起来, 中间用 `; ` 分隔
  3. 粘到下面

JUEJIN_UUID 从浏览器任意 juejin api 请求的 URL query 抠 (例: ?aid=2608&uuid=<这串>)
"""


def run_setup(platform: str = "juejin") -> None:
    if platform != "juejin":
        raise SystemExit(f"v0.3 只支持 juejin setup，{platform} 待后续 adapter")

    print(GUIDE)
    cookie = input("JUEJIN_COOKIE > ").strip()
    if not cookie:
        raise SystemExit("cookie 必填，取消")
    uuid = input("JUEJIN_UUID > ").strip()
    if not uuid:
        raise SystemExit("uuid 必填，取消")

    env_path = Path(os.path.expanduser("~/.web-publish/.env"))
    env_path.parent.mkdir(parents=True, exist_ok=True)
    env_path.write_text(
        f"# web-publish v0.3 — generated by `web-publish setup`\n"
        f"JUEJIN_COOKIE={cookie}\n"
        f"JUEJIN_AID=2608\n"
        f"JUEJIN_UUID={uuid}\n",
        encoding="utf-8",
    )
    try:
        os.chmod(env_path, 0o600)
    except OSError:
        pass  # Windows 没 chmod, 跳过
    print(f"\n✓ 写入 {env_path} (权限 600)")
    print("跑 `web-publish health juejin` 验证")
